apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-admin
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts-jdk11
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/jenkins_home/gcp/gsm-sa.json
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: jenkins-config
          mountPath: /var/jenkins_home/casc_configs/jenkins.yaml
          subPath: jenkins.yaml
        - name: jenkins-gsm-sa
          mountPath: /var/jenkins_home/gcp
          readOnly: true
        envFrom:
        - secretRef:
            name: jenkins
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pv-claim
      - name: jenkins-config
        configMap:
          name: casc-configs
      - name: jenkins-gsm-sa
        secret:
          secretName: gcp-sa-secret